import React from 'react';
import { useTheme } from '../context/ThemeContext';

const About = () => {
  const { theme } = useTheme();
  const dark = theme === 'dark';
  return (
    <div className={`px-4 py-20 min-h-screen ${dark ? 'bg-black text-white' : 'bg-white text-gray-900'}`}>
      <div className="max-w-5xl mx-auto space-y-10">
        <div className="text-center">
          <h1 className={`text-4xl md:text-5xl font-extrabold mb-4 ${dark ? 'text-[#00cc88]' : 'text-[#009966]'}`}>About HealthMate</h1>
          <p className={`text-lg ${dark ? 'text-gray-400' : 'text-gray-600'}`}>
            HealthMate is a personal health vault. Upload your lab reports, prescriptions or imaging results,
            get plain-English and Roman Urdu summaries generated by AI, and track vitals like blood pressure,
            blood sugar and weight—all in one place.
          </p>
        </div>
        <div className={`rounded-2xl p-8 border ${dark ? 'bg-gray-900 border-[#009966] border-opacity-30' : 'bg-gray-50 border-[#009966] border-opacity-20'}`}>
          <h2 className={`text-2xl font-bold mb-4 ${dark ? 'text-[#00cc88]' : 'text-[#009966]'}`}>What we do</h2>
          <ul className="space-y-3 text-sm">
            <li className="flex items-start gap-2">
              <span className={dark ? 'text-[#00cc88]' : 'text-[#009966]'}>✓</span>
              <span>Secure, fast uploads to Cloudinary with preview</span>
            </li>
            <li className="flex items-start gap-2">
              <span className={dark ? 'text-[#00cc88]' : 'text-[#009966]'}>✓</span>
              <span>Gemini-powered summaries in English + Roman Urdu</span>
            </li>
            <li className="flex items-start gap-2">
              <span className={dark ? 'text-[#00cc88]' : 'text-[#009966]'}>✓</span>
              <span>Key highlights, doctor questions, diet tips</span>
            </li>
            <li className="flex items-start gap-2">
              <span className={dark ? 'text-[#00cc88]' : 'text-[#009966]'}>✓</span>
              <span>Timeline view combining reports and vitals</span>
            </li>
          </ul>
        </div>
        <div className={`rounded-2xl p-8 border ${dark ? 'bg-gray-900 border-red-900' : 'bg-red-50 border-red-200'}`}>
          <h2 className={`text-2xl font-bold mb-4 ${dark ? 'text-red-400' : 'text-red-700'}`}>⚠️ Important Notice</h2>
          <p className={`text-sm ${dark ? 'text-gray-400' : 'text-gray-700'}`}>
            For education and understanding only — consult your doctor for treatment. This is not a medical device.
          </p>
        </div>
      </div>
    </div>
  );
};

export default About;
